server:
  port: 7003
spring:
  application:
    name: EVENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:9433/event_db
    username: marius
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  kafka:
    consumer:
      group-id: events-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    bootstrap-servers: http://localhost:9092
#  cloud:
#    config:
#      uri: http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    hostname: registry
