server:
  port: 7001

spring:
  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:7002/eureka
  instance:
    hostname: registry